set fallback

default:
    just list
    just --list

dev:
	npm run dev

build:
	npm run build

generate-types:
	npm run generate-types

lint:
	npm run lint

format:
	npm run format

test:
	npm run test

pre-commit:
	just build
	just lint
	just format
	just generate-types
	# add tests
