repos:
- repo: local
  hooks:
    # Backend Python hooks
    - id: ruff-format
      name: ruff format
      description: "Run 'ruff format' for Python formatting"
      entry: just backend format
      language: system
      types_or: [python, pyi, jupyter]
      pass_filenames: false
      require_serial: true
    - id: ruff-check
      name: ruff check
      description: "Run 'ruff check' for Python linting"
      entry: just backend lint
      language: system
      types_or: [python, pyi, jupyter]
      pass_filenames: false
      require_serial: true
    - id: sort-import
      name: sort imports
      description: "Run 'ruff check --select I --fix' to sort imports"
      entry: just backend sort-imports
      language: system
      types_or: [python, pyi, jupyter]
      pass_filenames: false
      require_serial: true
    - id: ty
      name: ty check
      description: "Run 'ty check' for Python type checking"
      entry: just backend type-check
      language: system
      types_or: [python, pyi, jupyter]
      pass_filenames: false
      require_serial: true
    - id: pytest
      name: pytest
      description: "Run 'pytest' for Python unit testing"
      entry: just backend test
      language: system
      types_or: [python, pyi, jupyter]
      pass_filenames: false
      require_serial: true
    - id: generate-docs
      name: generate docs
      description: "Run 'generate_docs.py' to update API documentation"
      entry: just backend generate-docs
      language: system
      types_or: [python, pyi, jupyter]
      pass_filenames: false
      require_serial: true
    # Frontend JavaScript hooks
    - id: openapi-typescript
      name: openapi-typescript
      description: "Updates TypeScript types from OpenAPI spec"
      entry: just frontend generate-types
      language: system
      types_or: [json]
      pass_filenames: false
      require_serial: true
    - id: prettier
      name: prettier
      description: "Run 'prettier' for JavaScript formatting"
      entry: just frontend format
      language: system
      types_or: [ts, tsx, jsx]
      pass_filenames: false
      require_serial: true
    - id: eslint
      name: eslint
      description: "Run 'eslint' for JavaScript linting"
      entry: just frontend lint
      language: system
      types_or: [ts, tsx, jsx]
      pass_filenames: false
      require_serial: true
    - id: build
      name: build
      description: "Run 'npm tsc -b && vite build' to build the frontend"
      entry: just frontend build
      language: system
      types_or: [ts, tsx, jsx]
      pass_filenames: false
      require_serial: true
