set fallback

default:
    just list
    just --list

dev:
    uv run uvicorn app.main:app --reload --port 8000

test:
    uv run pytest -vv

lint:
    uv run ruff check

sort-imports:
    uv run ruff check --select I --fix

format:
    uv run ruff format

type-check:
    uv run ty check app

generate-docs:
    uv run generate_docs.py
    git diff -s --exit-code openapi.json

pre-commit:
    just format
    just lint
    just sort-imports
    just type-check
    just generate-docs
    just test
