/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewPageRouteImport } from './routes/newPage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GemMapRouteImport } from './routes/gemMap'
import { Route as AdminPanelRouteImport } from './routes/adminPanel'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPageRoute = NewPageRouteImport.update({
  id: '/newPage',
  path: '/newPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GemMapRoute = GemMapRouteImport.update({
  id: '/gemMap',
  path: '/gemMap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/adminPanel',
  path: '/adminPanel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminPanel': typeof AdminPanelRoute
  '/gemMap': typeof GemMapRoute
  '/login': typeof LoginRoute
  '/newPage': typeof NewPageRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminPanel': typeof AdminPanelRoute
  '/gemMap': typeof GemMapRoute
  '/login': typeof LoginRoute
  '/newPage': typeof NewPageRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminPanel': typeof AdminPanelRoute
  '/gemMap': typeof GemMapRoute
  '/login': typeof LoginRoute
  '/newPage': typeof NewPageRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminPanel'
    | '/gemMap'
    | '/login'
    | '/newPage'
    | '/profile'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminPanel'
    | '/gemMap'
    | '/login'
    | '/newPage'
    | '/profile'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/adminPanel'
    | '/gemMap'
    | '/login'
    | '/newPage'
    | '/profile'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPanelRoute: typeof AdminPanelRoute
  GemMapRoute: typeof GemMapRoute
  LoginRoute: typeof LoginRoute
  NewPageRoute: typeof NewPageRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newPage': {
      id: '/newPage'
      path: '/newPage'
      fullPath: '/newPage'
      preLoaderRoute: typeof NewPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemMap': {
      id: '/gemMap'
      path: '/gemMap'
      fullPath: '/gemMap'
      preLoaderRoute: typeof GemMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminPanel': {
      id: '/adminPanel'
      path: '/adminPanel'
      fullPath: '/adminPanel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPanelRoute: AdminPanelRoute,
  GemMapRoute: GemMapRoute,
  LoginRoute: LoginRoute,
  NewPageRoute: NewPageRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
